# Dynamic configuration for Temporal
# This file contains runtime configuration that can be changed without restarting the server

# System limits
system.forceSearchAttributesCacheRefreshOnRead:
  - value: false
    constraints: {}

# History service configuration
history.persistenceMaxQPS:
  - value: 3000
    constraints: {}

# Matching service configuration  
matching.numTaskqueueReadPartitions:
  - value: 1
    constraints: {}

matching.numTaskqueueWritePartitions:
  - value: 1
    constraints: {}

# Frontend service configuration
frontend.enableClientVersionCheck:
  - value: false
    constraints: {}
